// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MutualExclusion.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::mutualexclusion;

class MutualExclusionHandler : virtual public MutualExclusionIf {
 public:
  MutualExclusionHandler() {
    // Your initialization goes here
  }

  void request() {
    // Your implementation goes here
    printf("request\n");
  }

  void release() {
    // Your implementation goes here
    printf("release\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MutualExclusionHandler> handler(new MutualExclusionHandler());
  shared_ptr<TProcessor> processor(new MutualExclusionProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

