/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mutualexclusion_CONSTANTS_H
#define mutualexclusion_CONSTANTS_H

#include "mutualexclusion_types.h"

namespace mutualexclusion {

class mutualexclusionConstants {
 public:
  mutualexclusionConstants();

};

extern const mutualexclusionConstants g_mutualexclusion_constants;

} // namespace

#endif
