/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mutualexclusion_constants.h"

namespace mutualexclusion {

const mutualexclusionConstants g_mutualexclusion_constants;

mutualexclusionConstants::mutualexclusionConstants() {
}

} // namespace

